# Generated by Django 2.2.12 on 2023-01-19 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(max_length=550, null=True)),
                ('image', models.ImageField(null=True, upload_to='branche')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('branch', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='service')),
                ('branchname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Branche')),
            ],
        ),
    ]
